// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnswersController from "./answers_controller"
application.register("answers", AnswersController)

import CardController from "./card_controller"
application.register("card", CardController)

import CardsController from "./cards_controller"
application.register("cards", CardsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
